### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by Keridos** [nicememe/VAC-Check#4]
The script is not working for me in the latest FF version (v44.0)

**Comment by dank** [comment]
Sorry. I no longer develop this extension. Check out this Chrome extension. https://chrome.google.com/webstore/detail/ban-checker-for-steam/canbadmphamemnmdfngmcabnjmjgaiki?hl=en

or the source: https://github.com/ge-ku/Ban-Checker-for-Steam I don't think there's a FF version of this extension however.
